apiVersion: v1
kind: Service
metadata:
  labels:
    app: mern-app-prd
    component: backend
  name: backend-svc
  namespace: mern-app-prd
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: mern-app-prd
    component: backend
  type: NodePort
