apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mern-app-prd
    component: database
  name: database-pvc
  namespace: mern-app-prd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  storageClassName: sc-nas-svm1