apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-svc
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-svc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: frontend-svc
    spec:
      containers:
        - image: mmodi/frontend-prd:latest
          imagePullPolicy: ""
          name: frontend
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
