kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: mern-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-mern-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: nginx
